<?php /* @var $this DEG_SiblingNav_Block_Navigation */ ?>

<?php if (!Mage::registry('current_category')): ?>
    <?php return; ?>
<?php endif; ?>

<?php $_categories = $this->getParentChildCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>

<?php if ($_count): ?>
    <div class="block block-layered-nav">
        <div class="block-content">
            <dl id="narrow-by-list2">
                <dd>
                    <ol>
                        <?php foreach ($_categories as $_category): ?>
                            <?php if($_category->getIsActive()): ?>
                                <li>
                                    <a href="<?php echo $this->getCategoryUrl($_category) ?>"<?php if ($this->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $this->escapeHtml($_category->getName()) ?></a>
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </ol>
                </dd>
            </dl>
        </div>
    </div>
<?php endif; ?>
